/** スキルタイプの定義 */
export const SKILL_TYPE_KEY = {
  heartCaptcha: 'ハートキャプチャ系',
  loveAttract: 'ラブアトラクト系',
  voltage: 'ボルテージ系',
  mental: 'メンタル系',
  extend: '手札枚数変更系',
  boost: 'ブースト系',
  AP: 'AP変化系',
  other: 'その他',
} as const;
export type skillTypeKeyTypes = keyof typeof SKILL_TYPE_KEY;

/** 各スキルの詳細を定義する定数 */
export const SKILL_DETAIL = {
  HEART_CAPTCHA: {
    name_ja: 'ハートキャプチャ',
    name_en: 'heartCaptcha',
    COLOR_CODE: 'red',
    DESCRIPTION: 'ハートを獲得する。',
    SKILL_TYPE_KEY: 'heartCaptcha',
  },
  LOVE_ATTRACT: {
    name_ja: 'ラブアトラクト',
    name_en: 'loveAttract',
    COLOR_CODE: 'lime-darken-3',
    DESCRIPTION: '次回ハート回収時、獲得するLOVEが増加する。',
    SKILL_TYPE_KEY: 'loveAttract',
  },
  LOVE_ATTRACT_SECTION: {
    name_ja: 'ラブアトラクト(セクション)',
    name_en: 'loveAttractSection',
    COLOR_CODE: 'lime-darken-3',
    DESCRIPTION: 'このセクション中、獲得するLOVEが増加する。',
    SKILL_TYPE_KEY: 'loveAttract',
  },
  LOVE_ATTRACT_STAGE: {
    name_ja: 'ラブアトラクト(ステージ)',
    name_en: 'loveAttractStage',
    COLOR_CODE: 'lime-darken-3',
    DESCRIPTION: 'このステージ中、獲得するLOVEが増加する。',
    SKILL_TYPE_KEY: 'loveAttract',
  },
  VOLTAGE_GAIN: {
    name_ja: 'ボルテージゲイン',
    name_en: 'voltageGain',
    COLOR_CODE: 'lime-darken-4',
    DESCRIPTION: 'ボルテージPt.を獲得する。',
    SKILL_TYPE_KEY: 'voltage',
  },
  VOLTAGE_REDUCE: {
    name_ja: 'ボルテージレデュース',
    name_en: 'voltageReduce',
    COLOR_CODE: 'lime-darken-4',
    DESCRIPTION: 'ボルテージPt.を減らす。',
    SKILL_TYPE_KEY: 'voltage',
  },
  MENTAL_RECOVER: {
    name_ja: 'メンタルリカバー',
    name_en: 'mentalRecover',
    COLOR_CODE: 'green',
    DESCRIPTION: 'メンタルを回復する。',
    SKILL_TYPE_KEY: 'mental',
  },
  MENTAL_REDUCE: {
    name_ja: 'メンタルレデュース',
    name_en: 'mentalReduce',
    COLOR_CODE: 'green',
    DESCRIPTION: 'メンタルを減らす。',
    SKILL_TYPE_KEY: 'mental',
  },
  MENTAL_DOWN_SECTION: {
    name_ja: 'メンタルダウン(セクション)',
    name_en: 'mentalDown_section',
    COLOR_CODE: 'green',
    DESCRIPTION:
      'このセクション中、メンタルが0になってもメンタルダウンしなくなる。',
    SKILL_TYPE_KEY: 'mental',
  },
  MENTAL_DOWN_STAGE: {
    name_ja: 'メンタルダウン(ステージ)',
    name_en: 'mentalDown_stage',
    COLOR_CODE: 'green',
    DESCRIPTION:
      'このステージ中、メンタルが0になってもメンタルダウンしなくなる。',
    SKILL_TYPE_KEY: 'mental',
  },
  PROTECT_SECTION: {
    name_ja: 'プロテクト(セクション)',
    name_en: 'protect_section',
    COLOR_CODE: 'green',
    DESCRIPTION: 'このセクション中、メンタル減少を一定量無効化する。',
    SKILL_TYPE_KEY: 'mental',
  },
  PROTECT_STAGE: {
    name_ja: 'プロテクト(ステージ)',
    name_en: 'protect_stage',
    COLOR_CODE: 'green',
    DESCRIPTION: 'このステージ中、メンタル減少を一定量無効化する。',
    SKILL_TYPE_KEY: 'mental',
  },
  RESHUFFLE: {
    name_ja: 'リシャッフル',
    name_en: 'reshuffle',
    COLOR_CODE: 'purple',
    DESCRIPTION: '手札を全て捨てて、デッキから手札上限までスキルを引く。',
    SKILL_TYPE_KEY: 'other',
  },
  EXTEND_HAND: {
    name_ja: 'エクステンドハンド',
    name_en: 'extendHand',
    COLOR_CODE: 'purple',
    DESCRIPTION: '手札の上限枚数が増加する。',
    SKILL_TYPE_KEY: 'extend',
  },
  EXTENSIONS_SECTION: {
    name_ja: 'エクステンション(セクション)',
    name_en: 'extensions_section',
    COLOR_CODE: 'purple',
    DESCRIPTION: 'このセクション中、手札の上限枚数が増加する(最大8枚)。',
    SKILL_TYPE_KEY: 'extend',
  },
  EXTENSIONS_STAGE: {
    name_ja: 'エクステンション(ステージ)',
    name_en: 'extensions_stage',
    COLOR_CODE: 'purple',
    DESCRIPTION: 'このステージ中、手札の上限枚数が増加する(最大8枚)。',
    SKILL_TYPE_KEY: 'extend',
  },
  CARD_REDUCE_SECTION: {
    name_ja: '手札減少(セクション)',
    name_en: 'cardReduce_section',
    COLOR_CODE: 'purple',
    DESCRIPTION: 'このセクション中、手札の上限枚数が減少する。',
    SKILL_TYPE_KEY: 'extend',
  },
  CARD_REDUCE_STAGE: {
    name_ja: '手札減少(ステージ)',
    name_en: 'cardReduce_stage',
    COLOR_CODE: 'purple',
    DESCRIPTION: 'このステージ中、手札の上限枚数が減少する。',
    SKILL_TYPE_KEY: 'extend',
  },
  BOOST_HEART_CAPTCHA: {
    name_ja: 'ブースト(ハートキャプチャ)',
    name_en: 'boost_heartCaptcha',
    COLOR_CODE: 'red',
    DESCRIPTION:
      '一定の回数使用するスキルハート獲得効果による獲得数を増加させる。',
    SKILL_TYPE_KEY: 'boost',
  },
  BOOST_LOVE_ATTRACT: {
    name_ja: 'ブースト(ラブアトラクト)',
    name_en: 'boost_loveAttract',
    COLOR_CODE: 'lime-darken-3',
    DESCRIPTION: '一定の回数使用するラブアトラクトの効果を増加させる。',
    SKILL_TYPE_KEY: 'boost',
  },
  BOOST_VOLTAGE_GAIN: {
    name_ja: 'ブースト(ボルテージゲイン)',
    name_en: 'boost_voltageGain',
    COLOR_CODE: 'lime-darken-4',
    DESCRIPTION: '一定の回数使用するボルテージゲインの効果を増加させる。',
    SKILL_TYPE_KEY: 'boost',
  },
  BOOST_MENTAL_RECOVER: {
    name_ja: 'ブースト(メンタルリカバー)',
    name_en: 'boost_mentalRecover',
    COLOR_CODE: 'green',
    DESCRIPTION: '一定の回数使用するメンタルリカバーの効果を増加させる。',
    SKILL_TYPE_KEY: 'boost',
  },
  BOOST_MENTAL_PROTECT: {
    name_ja: 'ブースト(メンタルプロテクト)',
    name_en: 'boost_mentalProtect',
    COLOR_CODE: 'green',
    DESCRIPTION: '一定の回数使用するメンタルプロテクトの効果を増加させる。',
    SKILL_TYPE_KEY: 'boost',
  },
  BOOST_WIDE_HEART: {
    name_ja: 'ブースト(ワイドハート)',
    name_en: 'boost_wideHeart',
    COLOR_CODE: 'red',
    DESCRIPTION: '一定の回数使用するハート上限個数増加効果を増加させる。',
    SKILL_TYPE_KEY: 'boost',
  },
  BOOST_AMBIENCE: {
    name_ja: 'ブースト(アンビエンス)',
    name_en: 'boost_ambience',
    COLOR_CODE: 'lime-darken-4',
    DESCRIPTION: '一定の回数使用するムード変動効果を増加させる。',
    SKILL_TYPE_KEY: 'boost',
  },
  BOOST_ALL: {
    name_ja: 'ブースト(All)',
    name_en: 'boost_all',
    COLOR_CODE: 'purple',
    DESCRIPTION: '一定の回数使用するあらゆるスキル効果量を増幅する。',
    SKILL_TYPE_KEY: 'boost',
  },
  BOOST_ALL_SECTION: {
    name_ja: 'ブースト(セクション)',
    name_en: 'boost_all_section',
    COLOR_CODE: 'purple',
    DESCRIPTION: 'このセクション中、あらゆるスキル効果量を増幅する。',
    SKILL_TYPE_KEY: 'boost',
  },
  BOOST_ALL_STAGE: {
    name_ja: 'ブースト(ステージ)',
    name_en: 'boost_all_stage',
    COLOR_CODE: 'purple',
    DESCRIPTION: 'このステージ中、あらゆるスキル効果量を増幅する。',
    SKILL_TYPE_KEY: 'boost',
  },
  AP_GAIN: {
    name_ja: 'APゲイン',
    name_en: 'APGain',
    COLOR_CODE: '',
    DESCRIPTION: 'APを回復する。',
    SKILL_TYPE_KEY: 'AP',
  },
  AP_LOSS: {
    name_ja: 'APロス',
    name_en: 'APLoss',
    COLOR_CODE: '',
    DESCRIPTION: 'APを減少させる。',
    SKILL_TYPE_KEY: 'AP',
  },
  AP_REDUCE: {
    name_ja: 'APレデュース',
    name_en: 'APReduce',
    COLOR_CODE: 'purple',
    DESCRIPTION: 'スキルの消費APを減少させる。',
    SKILL_TYPE_KEY: 'AP',
  },
  AP_REDUCE_ALL: {
    name_ja: 'APレデュース(手札全て)',
    name_en: 'APReduce_all',
    COLOR_CODE: 'purple',
    DESCRIPTION: '手札の全てのスキルの消費APを減少させる。',
    SKILL_TYPE_KEY: 'AP',
  },
  AP_REDUCE_DECK_ALL: {
    name_ja: 'APレデュース(デッキ内全て)',
    name_en: 'APReduce_deckAll',
    COLOR_CODE: 'purple',
    DESCRIPTION: 'デッキ内の全てのスキルの消費APを減少させる。',
    SKILL_TYPE_KEY: 'AP',
  },
  AP_REDUCE_HEART: {
    name_ja: 'APレデュース(ハート系)',
    name_en: 'APReduce_heart',
    COLOR_CODE: 'purple',
    DESCRIPTION:
      '手札のメイン効果にスキルハート獲得効果を持つスキルの消費APを減少させる。',
    SKILL_TYPE_KEY: 'AP',
  },
  AP_REDUCE_VOLTAGE_GAIN: {
    name_ja: 'APレデュース(ボルテージ系)',
    name_en: 'APReduce_voltageGain',
    COLOR_CODE: 'purple',
    DESCRIPTION:
      '手札のメイン効果にボルテージ増加効果を持つスキルの消費APを減少させる。',
    SKILL_TYPE_KEY: 'AP',
  },
  AP_REDUCE_DECK_CERISE_BOUQUET: {
    name_ja: 'APレデュース(スリーズブーケ)',
    name_en: 'APReduce_deck_ceriseBouquet',
    COLOR_CODE: 'purple',
    DESCRIPTION: 'デッキにあるスリーズブーケのスキルの消費APを減少させる。',
    SKILL_TYPE_KEY: 'AP',
  },
  AP_REDUCE_DECK_DRESS_CARD: {
    name_ja: 'APレデュース(ドレスカード)',
    name_en: 'APReduce_deck_dressCard',
    COLOR_CODE: 'purple',
    DESCRIPTION: 'デッキにあるドレスカードの消費APを減少させる。',
    SKILL_TYPE_KEY: 'AP',
  },
  AP_QUICK: {
    name_ja: 'ヒートアップ',
    name_en: 'APQuick',
    COLOR_CODE: 'lime-darken-3',
    DESCRIPTION: 'AP回復速度を上昇させる。',
    SKILL_TYPE_KEY: 'heartCaptcha',
  },
  AP_SLOW: {
    name_ja: 'AP回復速度低下',
    name_en: 'APSlow',
    COLOR_CODE: '',
    DESCRIPTION: 'AP回復速度を低下させる。',
    SKILL_TYPE_KEY: 'AP',
  },
  HEART_LIMIT_UP: {
    name_ja: 'ワイドハート',
    name_en: 'heartLimitUp',
    COLOR_CODE: 'red',
    DESCRIPTION: 'ハート数の上限を増加させる。',
    SKILL_TYPE_KEY: 'heartCaptcha',
  },
  ADD_CARD: {
    name_ja: 'カード追加',
    name_en: 'addCard',
    COLOR_CODE: 'purple',
    DESCRIPTION: 'カードを山札に追加する。',
    SKILL_TYPE_KEY: 'heartCaptcha',
  },
  ADD_SPECIAL_APPEAL: {
    name_ja: 'SA追加',
    name_en: 'addSA',
    COLOR_CODE: 'purple',
    DESCRIPTION: 'スペシャルアピールを追加する。',
    SKILL_TYPE_KEY: 'other',
  },
  IGNITION: {
    name_ja: 'イグニッション',
    name_en: 'ignition',
    COLOR_CODE: 'purple',
    DESCRIPTION: '特定条件で効果が変化する。',
    SKILL_TYPE_KEY: 'other',
  },
  MODE_CHANGE: {
    name_ja: 'モードチェンジ',
    name_en: 'modeChange',
    COLOR_CODE: 'purple',
    DESCRIPTION: 'スキルの効果を変化させる。',
    SKILL_TYPE_KEY: 'other',
  },
  COOL_TIME: {
    name_ja: 'クールタイム',
    name_en: 'coolTime',
    COLOR_CODE: '',
    DESCRIPTION: 'スキル使用時、クールタイムが発生する。',
    SKILL_TYPE_KEY: 'other',
  },
  INFINITY_AP_SECTION: {
    name_ja: 'AP無限(セクション)',
    name_en: 'infinity_AP_section',
    COLOR_CODE: '',
    DESCRIPTION: 'このセクション中、APを無限にする。',
    SKILL_TYPE_KEY: 'other',
  },
  INFINITY_AP_STAGE: {
    name_ja: 'AP無限(ステージ)',
    name_en: 'infinity_AP_stage',
    COLOR_CODE: '',
    DESCRIPTION: 'このステージ中、APを無限にする。',
    SKILL_TYPE_KEY: 'other',
  },
  INFINITY_VOLTAGE_SECTION: {
    name_ja: 'ボルテージ無限(セクション)',
    name_en: 'infinity_voltage_section',
    COLOR_CODE: '',
    DESCRIPTION: 'このセクション中、ボルテージを無限にする。',
    SKILL_TYPE_KEY: 'other',
  },
  INFINITY_VOLTAGE_STAGE: {
    name_ja: 'ボルテージ無限(ステージ)',
    name_en: 'infinity_voltage_stage',
    COLOR_CODE: '',
    DESCRIPTION: 'このステージ中、ボルテージを無限にする。',
    SKILL_TYPE_KEY: 'other',
  },
  INFINITY_MENTAL_SECTION: {
    name_ja: 'メンタル無限(セクション)',
    name_en: 'infinity_mental_section',
    COLOR_CODE: '',
    DESCRIPTION: 'このセクション中、メンタルを無限にする。',
    SKILL_TYPE_KEY: 'other',
  },
  INFINITY_MENTAL_STAGE: {
    name_ja: 'メンタル無限(ステージ)',
    name_en: 'infinity_mental_stage',
    COLOR_CODE: '',
    DESCRIPTION: 'このステージ中、メンタルを無限にする。',
    SKILL_TYPE_KEY: 'other',
  },
  SKILL_USE_HANDS_CARD: {
    name_ja: 'スキル使用(手札)',
    name_en: 'skillUse-handsCard',
    COLOR_CODE: '',
    DESCRIPTION: '手札の他の全スキルを同時に使用する。',
    SKILL_TYPE_KEY: 'other',
  },
  CHANGE_DECK: {
    name_ja: 'チェンジデッキ',
    name_en: 'changeDeck',
    COLOR_CODE: 'purple',
    DESCRIPTION: 'デッキを入れ替える。',
    SKILL_TYPE_KEY: 'other',
  },
  CHALLENGE: {
    name_ja: 'チャレンジ',
    name_en: 'challenge',
    COLOR_CODE: '',
    DESCRIPTION: 'ランダムにチャレンジが発生する。',
    SKILL_TYPE_KEY: 'other',
  },
  DRIVE_IGNITION: {
    name_ja: 'ドライブイグニッション',
    name_en: 'driveIgnition',
    COLOR_CODE: '',
    DESCRIPTION:
      'イグニッションモードになった回数に応じて、様々な効果が発動する。',
    SKILL_TYPE_KEY: 'other',
  },
  VIBES_SECTION: {
    name_ja: 'バイブス(セクション)',
    name_en: 'vibes_section',
    COLOR_CODE: 'lime-darken-4',
    DESCRIPTION: 'このセクション中、ビートハートの出現個数を増加させる。',
    SKILL_TYPE_KEY: 'other',
  },
  VIBES_STAGE: {
    name_ja: 'バイブス(ステージ)',
    name_en: 'vibes_stage',
    COLOR_CODE: 'lime-darken-4',
    DESCRIPTION: 'このステージ中、ビートハートの出現個数を増加させる。',
    SKILL_TYPE_KEY: 'other',
  },
  AMBIENCE_SECTION: {
    name_ja: 'アンビエンス(セクション)',
    name_en: 'ambience_section',
    COLOR_CODE: 'lime-darken-4',
    DESCRIPTION: 'このセクション中、ムード値を変化させる。',
    SKILL_TYPE_KEY: 'other',
  },
  AMBIENCE_STAGE: {
    name_ja: 'アンビエンス(ステージ)',
    name_en: 'ambience_stage',
    COLOR_CODE: 'lime-darken-4',
    DESCRIPTION: 'このステージ中、ムード値を変化させる。',
    SKILL_TYPE_KEY: 'other',
  },
  IMITATION: {
    name_ja: 'イミテーション',
    name_en: 'imitation',
    COLOR_CODE: 'purple',
    DESCRIPTION:
      'カードがステージにセットされ、特定の獲得したものを吸収する。その後、特定の効果を発動し、捨札に移動する。',
    SKILL_TYPE_KEY: 'other',
  },
  SOUND: {
    name_ja: 'サウンド',
    name_en: 'sound',
    COLOR_CODE: 'red',
    DESCRIPTION:
      'ムードが一定値以上もしくは一定値以下になると、特定の効果を発動する。',
    SKILL_TYPE_KEY: 'other',
  },
  DRAW: {
    name_ja: 'ドロー',
    name_en: 'draw',
    COLOR_CODE: '',
    DESCRIPTION: '特定のメンバーのカードをドローする確率がアップする。',
    SKILL_TYPE_KEY: 'other',
  },
} as const;
export type skillDetail = keyof typeof SKILL_DETAIL;
