/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/CardList': RouteRecordInfo<'/CardList', '/CardList', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/ItemList': RouteRecordInfo<'/ItemList', '/ItemList', Record<never, never>, Record<never, never>>,
    '/License': RouteRecordInfo<'/License', '/License', Record<never, never>, Record<never, never>>,
    '/MusicList': RouteRecordInfo<'/MusicList', '/MusicList', Record<never, never>, Record<never, never>>,
    '/Simulation': RouteRecordInfo<'/Simulation', '/Simulation', Record<never, never>, Record<never, never>>,
    '/WithStarMgr': RouteRecordInfo<'/WithStarMgr', '/WithStarMgr', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/CardList.vue': {
      routes: '/CardList'
      views: never
    }
    'src/pages/Home.vue': {
      routes: '/Home'
      views: never
    }
    'src/pages/ItemList.vue': {
      routes: '/ItemList'
      views: never
    }
    'src/pages/License.vue': {
      routes: '/License'
      views: never
    }
    'src/pages/MusicList.vue': {
      routes: '/MusicList'
      views: never
    }
    'src/pages/Simulation.vue': {
      routes: '/Simulation'
      views: never
    }
    'src/pages/WithStarMgr.vue': {
      routes: '/WithStarMgr'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
